name: Coding Standards

on: [ pull_request ]

jobs:
  phpcs:
    name: PHP coding standards
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: composer, cs2pr

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check coding standards using Laravel Pint
        run: vendor/bin/pint --test --format=checkstyle | cs2pr
